name: Terraform
on: pull_request

permissions: read-all

jobs:
  format_and_docs:
    name: Format & Docs
    runs-on: ubuntu-latest

    permissions:
      # Allows Dependabot to push docs updates
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # As required by 'terraform-docs/gh-actions':
          # https://github.com/terraform-docs/gh-actions#auto-commit-changes
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: <1.3

      - name: Terraform Format
        run: terraform fmt -recursive .

      - name: Terraform Docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          # This action will push a commit of the changes
          # Which will also include the 'terraform fmt' changes
          git-push: true
          git-commit-message: Terraform format, docs